// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アプリエントリ。割当キーで対象プロセスのウィンドウを最前面化、未起動なら `command` で起動する。
 */
export interface AppEntry {
  /**
   * ディスパッチキー（無指定可）。
   */
  key?: string;
  /**
   * 対象プロセス名（ウィンドウ検索に使用）。
   */
  process: string;
  /**
   * 起動コマンド（省略時は `process` をフォールバックとして使用）。
   */
  command?: string;
}

/**
 * muhenkan-switch のトップレベル設定（`config.toml` のルート）。
 */
export interface Config {
  /**
   * 検索エンジン一覧（割当キーで起動）。
   */
  search: Record<string, SearchEntry>;
  /**
   * フォルダ一覧（割当キーで開く）。
   */
  folders: Record<string, FolderEntry>;
  /**
   * アプリ一覧（割当キーでウィンドウ切替・起動）。
   */
  apps: Record<string, AppEntry>;
  /**
   * タイムスタンプ挿入設定。
   */
  timestamp: TimestampConfig;
  /**
   * 句読点スタイル。kanata の kbd ファイルに反映される。
   */
  punctuation_style: PunctuationStyle;
}

/**
 * フォルダエントリ。割当キーでファイルマネージャから対象フォルダを開く。
 */
export interface FolderEntry {
  /**
   * ディスパッチキー（無指定可）。
   */
  key?: string;
  /**
   * フォルダパス。`~/` 表記でホーム展開対応。
   */
  path: string;
}

/**
 * 句読点スタイル。kanata の kbd ファイルに反映される 4 種類。
 * TOML / JSON 上は `"、。"` のような文字列リテラルで表現される。
 */
export type PunctuationStyle = '、。' | '，．' | '，。' | '、．';

/**
 * 検索エンジンエントリ。割当キーで起動し、URL テンプレートにクエリを差し込んで検索する。
 */
export interface SearchEntry {
  /**
   * ディスパッチキー（無指定可）。`DISPATCH_KEYS` から選ぶ。
   */
  key?: string;
  /**
   * 検索 URL テンプレート。`{query}` プレースホルダがクエリ文字列に置換される。
   */
  url: string;
}

/**
 * タイムスタンプ挿入設定。ファイル名等にタイムスタンプを付与するときの形式を制御する。
 */
export interface TimestampConfig {
  /**
   * フォーマット文字列（chrono strftime 互換、例: `%Y%m%d`）。
   */
  format: string;
  /**
   * 挿入位置: `"before"` | `"after"`。
   */
  position: string;
  /**
   * 区切り文字。空文字で区切りなし。
   */
  delimiter: string;
}
