// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppEntry {
  key?: string;
  process: string;
  command?: string;
}

export interface Config {
  search: Record<string, SearchEntry>;
  folders: Record<string, FolderEntry>;
  apps: Record<string, AppEntry>;
  timestamp: TimestampConfig;
  punctuation_style: '、。' | '，．' | '，。' | '、．';
}

export interface FolderEntry {
  key?: string;
  path: string;
}

export interface SearchEntry {
  key?: string;
  url: string;
}

export interface TimestampConfig {
  format: string;
  position: string;
  delimiter: string;
}
